### ISSUE TITLE
Remove checkmarks from issue templates 

### ISSUE THREAD

**Issue by austinpray** [roots/.github#2]
Right now having checkboxes in the issue template

```
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing request
* [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community
```

Makes checklists useless in the GitHub issues UI because every single issue will have “3/3 tasks completed”

![9C5BBF0B-53A0-47D0-94A9-B26D8D4AFA7C](https://user-images.githubusercontent.com/2192970/58600998-7a26cf80-824c-11e9-926a-40bc49632466.jpeg)

We should just remove these checklist items or move them into the comment.

**Comment by retlehs** [comment]
i thought that the issue forms fixed this but it didnt

this is also annoying:

![image](https://user-images.githubusercontent.com/115911/147988911-00199ef2-a0a4-4e3c-9589-efaadbb7b780.png)

**Comment by retlehs** [comment]
#16
